#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

PYSTYLE_IGNORE=""

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
		LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
echo "Checking whitespace on committed files..."
git diff-index --check --cached $against -- || exit $?

toplevel_dir=$(git rev-parse --show-toplevel)

# Redirect keyboard input to standard in
exec < /dev/tty

# Also check that staged files have not since been modified
all_staged_files=$(git diff $against --cached --name-only)
all_modified_files=$(git ls-files -m)

for file in $all_staged_files; do
	if [ "${all_modified_files#*$file}" != "$all_modified_files" ]; then
		echo "You have forgotten to commit some changes for $file"
		while true; do
			read -p "Cancel commit? (Y/n) " cancel
			if [ "$cancel" = "" ]; then
				cancel='Y'
			fi
			case $cancel in
				[Yy] ) echo "Commit cancelled"; exit 1;;
				[Nn] ) break;;
				* ) echo "Please answer y or n for yes or no.";;
			esac
		done
	fi
done

# Run pytest suite if any .py files are in tests/
if [ -f ${toplevel_dir}/tests/*.py ]; then
	echo "Running pytest..."
	/usr/bin/env pytest || exit $?
else
	echo "No .py files found in ${toplevel_dir}/tests. Skipping pytest..."
fi

# Run pycodestyle on source .py files
staged_py_files=$(git diff $against --cached --name-only | grep \.py$)

if [ -n "$staged_py_files" ]; then
	echo "Running pycodestyle on committed python files..."
	for py_file in $staged_py_files; do
		if [ -e $py_file ]; then
			/usr/bin/env pycodestyle --exclude="$PYSTYLE_IGNORE" $py_file || exit $?
		fi
	done
else
	echo "No .py files committed. Skipping pycodestyle..."
fi

# Run cppcheck on C/C++ source files
staged_source_files=$(git diff $against --cached --name-only | grep -Ee '\.(c|cpp|cc|cxx)$')

if [ -n "$staged_source_files" ]; then
	echo "Running cppcheck on committed C/C++ source files..."
	cppcheck --enable=all --error-exitcode=1 $staged_source_files -I include/ || exit $?
else
	echo "No C/C++ source files committed. Skipping cppcheck..."
fi
